name: Docker Publish 
on: 
  workflow_dispatch: 
    branches: 
      - "dev" 
env: 
  app: smartsaw-adapter  
jobs:  
  build-and-push:    
    runs-on: ubuntu-latest     
    steps:     
      - name: Checkout code        
        uses: actions/checkout@v2       
        
      - name: Pull Docker image        
        run: docker pull --platform linux/arm64 doru2001/smartsaw_docker_base_1_ubuntu_22.04_arm64:latest       
      
      - name: Tag Docker image        
        run: docker tag doru2001/smartsaw_docker_base_1_ubuntu_22.04_arm64:latest enola777/basecheck:arm64       
        
      - name: Log in to Docker Hub        
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}       
        
      - name: Push Docker image        
        run: docker push enola777/basecheck:arm64
    
