name: Docker Publish 
on: 
  workflow_dispatch: 
    branches: 
      - "dev" 
env: 
  app: smartsaw-adapter 
jobs: 
  build_and_push: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4 
      - name: Set up QEMU 
        uses: docker/setup-qemu-action@v3 
      - name: Login to DockerHub 
        uses: docker/login-action@v3 
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: create version 
        id: version 
        run: | 
          echo "VERSION=$(echo ${{ github.ref_name }})" >> $GITHUB_ENV 
          echo "MAJOR_VERSION=$(echo ${{ github.ref_name }} | sed -E 's/^([0-9]+)\.([0-9]+)\..+/\1.\2/')" >> $GITHUB_ENV 
      - name: Build and push Docker images (amd64) 
        uses: docker/build-push-action@v5 
        with: 
          context: . 
          file: scripts/Dockerfile_amd64 
          platforms: linux/amd64 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smartsaw_docker_base_ubuntu_22.04:amd64 
          push: true 
      - name: Build and push Docker images (arm64) 
        uses: docker/build-push-action@v5 
        with: 
          context: . 
          file: scripts/Dockerfile_arm64 
          platforms: linux/arm64 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smartsaw_docker_base_ubuntu_22.04:arm64 
          push: true 
